# Generated by Django 4.2.3 on 2023-09-17 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libraryapp', '0055_bookrequest_returned'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverdueBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('days_overdue', models.PositiveIntegerField()),
                ('fine_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('book_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.bookrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
