# Generated by Django 4.2.3 on 2023-09-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0056_overduebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrequest',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
